# Put config in this section valid for all environments
# Environment specific configs will override this section
all:
  # If disabled set to true, links to Login/Register pages will be hidden,
  # but pages will still be available by direct link
  authentication_disabled: true

# Development env specific configs
development:
  secret_key_base:   xg751p8ngbyKBxVxZ21wXp8098HjQZrM
  devise_secret_key: 8278n3qghIRus1M5quC2Ya54bH99mOgg

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@domain.com
    host: domain.com
    smtp:
      address: smtp.mandrillapp.com
      user: username
      port: 587
      password: password

# Configs for unit tests
test:
  secret_key_base: xg751p8ngbyKBxVxZ21wXp8098HjQZrM
  devise_secret_key: xg751p8ngbyKBxVxZ21wXp8098HjQZrM

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@domain.com
    host: localhost:3000
    smtp:
      address: smtp.mandrillapp.com
      user: username
      port: 587
      password: password

# Production configs
production:
  secret_key_base: d56101e277742dd1c31d52fa6ac778e3a2c7661496366d46963eabe2479f7eb41312ce57193b53d1b9c3700cf229eef65bf4b805adf40431c42787fb450620ad
  devise_secret_key: a91ccc1ef5b2b48292dbd1a5c7787acfc23d8d2cf3beb7265f34534cbd0bd4cb2c64e8e06d89d5ed3446aad042611a27b0c3cdbe049550809cbcdae2f49ec8ac

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@domain.com
    host: domain.com
    smtp:
      address: smtp.mandrillapp.com
      user: <%= ENV['MAILER_USER'] %>
      port: 587
      password: <%= ENV['MAILER_PASSWORD'] %>
