development:
  adapter: mysql2
  host: localhost
  database: ror_commerce_development
  username: root
  password: ravi@123
  pool: 5
  timeout: 5000


test:
  adapter: mysql2
  host: localhost
  database: ror_commerce_test
  username: root
  password: ravi@123
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: localhost
  pool: 5
  timeout: 5000
  port: /var/run/mysqld/mysqld.sock

  # production:
  # adapter: postgresql
  # encoding: unicode
  # pool: 5
